// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyFlXNUkNZNn8_Fk7IsRkxgcr3akgfHJY',
    appId: '1:847486248111:android:966c018d3f453943dca05a',
    messagingSenderId: '847486248111',
    projectId: 'eventos-97d51',
    storageBucket: 'eventos-97d51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTbY2-AaE1B4e0if1gnFtt-2stoOhiD4g',
    appId: '1:847486248111:ios:e153f9aef3a3dc59dca05a',
    messagingSenderId: '847486248111',
    projectId: 'eventos-97d51',
    storageBucket: 'eventos-97d51.appspot.com',
    androidClientId: '847486248111-18gpvlv0n96vpugamnfqooc486db3paj.apps.googleusercontent.com',
    iosClientId: '847486248111-fejnspncdh3m7s891obm4bqc5g58fnm9.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventosPartenaires',
  );
}
